=== mousterchung/class_schedule/dtd/room.dtd
<!DOCTYPE class-schedule [
	<!ELEMENT class-schedule (class-name, weekday, weekday, weekday, weekday, weekday, weekday)>
		<!--<!ATTLIST class-schedule type (class|subject|teacher|room)>-->
		<!ATTLIST class-schedule type CDATA #FIXED room>
		<!ATTLIST class-schedule id ID #REQUIRED>
		<!ATTLIST class-schedule name CDATA #REQUIRED>
		<!ATTLIST class-schedule year CDATA #REQUIRED>
		<!ATTLIST class-schedule semester (1|2) #REQUIRED>
		
		<!ELEMENT weekday (section, section, section, section, section, section, section, section, section)>
			<!ATTLIST weekday day (1|2|3|4|5|6) #REQUIRED>
			
			<!ELEMENT section (classes*)>
				<!ATTLIST section section (0|1|2|3|4|5|6|7|8|9) #REQUIRED>
				<!ATTLIST section parttime (true|false) false>
				<!ATTLIST section oddevenweek (odd|even|all) all>
				
				<!ELEMENT classes (subject, teacher+, room?)<
					<!ATTLIST classes parttime (true|false) false>
					
					<!ELEMENT class (#PCDATA)>
						<!ATTLIST class id IDREF #REQUIRED>
					<!ELEMENT subject (#PCDATA)>
						<!ATTLIST subject id IDREF #REQUIRED>
					<!ELEMENT teacher (#PCDATA)>
						<!ATTLIST teacher id IDREF #REQUIRED>
					<!--<!ELEMENT room (#PCDATA)>
						<!ATTLIST room id IDREF #REQUIRED>-->
]>

=== mousterchung/class_schedule/data/template_/rtemplate.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="../../xsl/room.xsl"?>
<!DOCTYPE class-schedule SYSTEM "../../dtd/room.dtd">
<class-schedule type="room" id="{room-id}" name="{room-name}" year="template" semester="">
	<weekday day="1">
		<section section="0">
		</section>
		<section section="1">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="2">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="3">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="4">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="5">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="6">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="7">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="8">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="9">
		</section>
	</weekday>
	<weekday day="2">
		<section section="0">
		</section>
		<section section="1">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="2">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="3">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="4">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="5">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="6">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="7">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="8">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="9">
		</section>
	</weekday>
	<weekday day="3">
		<section section="0">
		</section>
		<section section="1">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="2">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="3">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="4">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="5">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="6">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="7">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="8">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="9">
		</section>
	</weekday>
	<weekday day="4">
		<section section="0">
		</section>
		<section section="1">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="2">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="3">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="4">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="5">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="6">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="7">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="8">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="9">
		</section>
	</weekday>
	<weekday day="5">
		<section section="0">
		</section>
		<section section="1">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="2">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="3">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="4">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="5">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="6">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="7">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="8">
			<classes>
				<subject id="stemplate">{s-name}</subject>
				<class id="ctemplate">{c-name}</class>
				<teacher id="ttemplate">{t-name}</teacher>
			</classes>
		</section>
		<section section="9">
		</section>
	</weekday>
	<weekday day="6">
		<section section="0">
		</section>
		<section section="1">
		</section>
		<section section="2">
		</section>
		<section section="3">
		</section>
		<section section="4">
		</section>
		<section section="5">
		</section>
		<section section="6">
		</section>
		<section section="7">
		</section>
		<section section="8">
		</section>
		<section section="9">
		</section>
	</weekday>
</class-schedule>
